name: Reusable Build and Push

on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
      registry:
        required: true
        type: string
      github_user:
        required: true
        type: string
      branch:
        required: true
        type: string
    secrets:
      ghcr_token:
        required: true
    outputs:
      full_image:
        description: "Full Docker image"
        value: ${{ jobs.build.outputs.full_image }}
      image_tag:
        description: "Docker image tag"
        value: ${{ jobs.build.outputs.image_tag }}

jobs:
  build:
    runs-on: ubuntu-latest

    outputs:
      full_image: ${{ steps.meta.outputs.full_image }}
      image_tag: ${{ steps.meta.outputs.image_tag }}

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}

      - name: Setup Docker
        uses: praneethsrinivas-devops/github-actions-workflows/.github/actions/docker-setup@main
        with:
          github_user: ${{ inputs.github_user }}
          ghcr_token: ${{ secrets.ghcr_token }}

      - name: Generate image tag
        id: meta
        run: |
          COMMIT=$(git rev-parse --short HEAD)
          TAG="${{ inputs.branch }}-$COMMIT-${GITHUB_RUN_NUMBER}"
          FULL_IMAGE="${{ inputs.registry }}/${{ inputs.github_user }}/${{ inputs.image_name }}:$TAG"
          echo "image_tag=$TAG" >> $GITHUB_OUTPUT
          echo "full_image=$FULL_IMAGE" >> $GITHUB_OUTPUT

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.full_image }}
