name: Kubernetes CI Test

on:
  workflow_call:
    inputs:
      namespace:
        required: true
        type: string
      full_image:
        required: true
        type: string
    secrets:
      ghcr_token:
        required: true

jobs:
  k8s-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Create kind cluster
      - name: Create kind cluster
        uses: helm/kind-action@v1

      # Login to GHCR
      - name: Login to GHCR
        run: echo "${{ secrets.ghcr_token }}" | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin

      - name: Create namespace
        run: kubectl create namespace ${{ inputs.namespace }}

      # Create GHCR image pull secret
      - name: Create image pull secret
        run: |
          kubectl create secret docker-registry github-pat-secret \
            --docker-server=ghcr.io \
            --docker-username=${{ github.actor }} \
            --docker-password=${{ secrets.ghcr_token }} \
            --docker-email=praneeth.srinivas1993@gmail.com \
            -n ${{ inputs.namespace }} \
            --dry-run=client -o yaml | kubectl apply -f -

      - name: Replace image
        run: |
          sed -i "s|IMAGE_PLACEHOLDER|${{ inputs.full_image }}|g" nginx-deployment.yaml
          cat nginx-deployment.yaml

      - name: Deploy
        run: |
          kubectl apply -n ${{ inputs.namespace }} -f .

      - name: Wait for rollout
        run: |
          kubectl rollout status deployment/my-nginx-deployment -n ${{ inputs.namespace }}
          sleep 30
          kubectl get pods -n nginx-dev

      - name: Show pods
        run: kubectl get pods -n ${{ inputs.namespace }}
