name: Reusable Kubernetes Deploy

on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string
      deploy_env:
        required: true
        type: string
      namespace:
        required: true
        type: string
    secrets:
      kubeconfig_data:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.deploy_env }}

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}

      - name: Setup Kubernetes
        uses: praneethsrinivas-devops/github-actions-workflows/.github/actions/kubectl-setup@main
        with:
          kubeconfig_data: ${{ secrets.kubeconfig_data }}

      - name: Deploy to cluster
        run: |
          kubectl apply -f nginx-deployment.yaml -n "${{ inputs.namespace }}"
          kubectl apply -f nginx-service.yaml -n "${{ inputs.namespace }}"
          kubectl rollout status deployment/my-nginx-deployment -n "${{ inputs.namespace }}"
